### PR TITLE
feat: make release 0.26.0

### PR DESCRIPTION
**Pull request by Pog3k**

### CODE REVIEW

**Review by sebastianpfischer — CHANGES_REQUESTED** [review]
4 issues still in the milestone: https://github.com/eclipse/kiso-testing/milestone/18
Can you provide more information why we should release 0.26.0?

**Review by sebclrsn — COMMENTED** [review]
pykiso_python_uds can be upgraded to 3.2.*

**Comment by Pog3k** [comment]
> 4 issues still in the milestone: https://github.com/eclipse/kiso-testing/milestone/18 Can you provide more information why we should release 0.26.0?

There also  bugfixes where users wait for it
grafik

Most important is also now that we support UDS on classic CAN which is an important feature...

We need faster release cycles.. lets talk in the next sync about it.

**Review by sebclrsn — APPROVED** [review]

**Review by TedRio — APPROVED** [review]

**Comment by Pog3k** [comment]
> pykiso_python_uds can be upgraded to 3.2.*

yupp, updatet info also in whats new

**Pull request merged**
